# Generated by Django 4.2.15 on 2024-08-23 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished', '0002_alter_finishedorder_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedorder',
            name='finished_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
