# Generated by Django 4.2.15 on 2024-08-25 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finished', '0003_alter_finishedorder_finished_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='finished_date',
        ),
        migrations.AlterField(
            model_name='finishedorder',
            name='finished_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
