# Generated by Django 4.2.15 on 2024-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_leftoverorder_leftoverproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverproduct',
            name='restock',
            field=models.BooleanField(default=True),
        ),
    ]
