# Generated by Django 4.2.15 on 2025-04-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                # ('description', tinymce.models.HTMLField(help_text='Descrição completa para exibição no site.')),
                ('image', models.ImageField(upload_to='kits/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_choices', models.PositiveIntegerField(help_text='Quantos itens dessa categoria o cliente pode escolher.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.kit')),
            ],
        ),
    ]
