# Generated by Django 4.2.15 on 2025-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_kit_kitoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='show_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
