# Generated by Django 4.2.15 on 2025-04-21 23:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_kit_show_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Descrição temporária', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
